# general configuration
fMRI_data_dir:           "resources/fMRI_data"
bold_glob_pattern:       "resources/fMRI_data/sub-{subject}/func/sub-{subject}_task-{task}{run_tag}_space-{space}_res-{resolution}_desc-{descriptor}_bold.nii.gz"
scans_to_be_excluded:    "resources/scan_exclude.json"
excluded_scans_for_task: "results/excluded_scans_for_task.json"

# dataset configuration
subjects:
  start: 1
  end: 345
tasks:
  - "21styear"
  - "bigbang"
  - "black"
  - "bronx"
  - "forgot"
  - "friends"
  - "himym"
  - "lucy"
  - "merlin"
  - "milkyway"
  - "milkywayoriginal"
  - "milkywaysynonyms"
  - "milkywayvodka"
  - "notthefallintact"
  - "notthefalllongscram"
  - "notthefallshortscram"
  - "pieman"
  - "piemanpni"
  - "prettymouth"
  - "santa"
#  - "schema"
  - "seinfeld"
  - "shame"
  - "shapesphysical"
  - "shapessocial"
  - "sherlock"
  - "slumlordreach"
  - "tunnel"
  - "upintheair"
  - "vinny"
run_tags:
  - ""
  - "_run-1"
  - "_run-2"
spaces:
  - "MNI152NLin2009cAsym"
resolutions:
  - "native"
descriptors:
  - "clean"

# subtasks of "schema" task
schema_subtasks:
  - "bigbang"
  - "friends"
  - "himym"
  - "santa"
  - "seinfeld"
  - "shame"
  - "upintheair"
  - "vinny"

# variants of "notthefall" task
notthefall_variants:
  - "notthefalllongscram"
  - "notthefallshortscram"

# atlas configuration
atlas:
  atlas_dir: "resources/atlases"
  n_rois: 200
  yeo_networks: 7