# dataset configuration
bold_glob_pattern: "resources/fMRI_data/sub-{subject}/func/sub-{subject}_task-{task}{run_tag}_space-{space}_res-{resolution}_desc-{descriptor}_bold.nii.gz"
subjects:
  start: 1
  end: 345
tasks:
  - "21styear"
  - "black"
  - "bronx"
  - "forgot"
  - "lucy"
#  - "merlin"
  - "milkyway"
  - "notthefallintact"
  - "notthefalllongscram"
  - "notthefallshortscram"
  - "pieman"
  - "piemanpni"
  - "prettymouth"
  - "schema"
#  - "shapesphysical"
#  - "shapessocial"
#  - "sherlock"
#  - "slumlordreach"
#  - "tunnel"
run_tags:
  - ""
  - "_run-1"
  - "_run-2"
spaces:
  - "MNI152NLin2009cAsym"
resolutions:
  - "native"
descriptors:
  - "clean"

# atlas configuration
atlas:
  atlas_dir: "resources/atlases"
  n_rois: 200
  yeo_networks: 7